services:
  shortener:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080"
    networks:
      - shortener-network
    volumes:
      - ../.env:/.env
    depends_on:
      redis:
        condition: service_healthy