services:
  shortener:
    build:
      dockerfile: build/Dockerfile
    ports:
      - "8080"
      - "8081"
    networks:
      - shortener-network
    volumes:
      - ../.env:/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${SERVER_HOST}${SERVER_ADDR}/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      redis:
        condition: service_healthy