{
 "title": "Shortener Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PR 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PR 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "GC 0.5",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.5\", job=\"shortener_server\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}