services:
  redis:
    image: redis:latest
    ports:
      - "6379"
    env_file:
      - .env
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: redis-server --requirepass ${REDIS_PASSWORD}
